openapi: 3.0.0
components:
  schemas:
    machineActivateStep1Request:
      type: object
      required:
        - hashId
        - secureToken
      properties:
        hashId:
          type: string
        secureToken:
          type: string
    machineActivateStep2Request:
      type: object
      required:
        - hashId
        - secureToken
        - machineIdentifier
      properties:
        hashId:
          type: string
        secureToken:
          type: string
        machineIdentifier:
          type: string
    uploadCalibrationDataRequest:
      type: object
    saveCheckupResultsRequest:
      type: object
      required:
        - time
        - staffId
        - minRange
        - maxRange
      properties:
        time:
          type: number
        reps:
          type: number
        staffId:
          type: number
        minRange:
          type: number
        maxRange:
          type: number
    saveWorkoutResultsRequest:
      type: object
      required:
        - time
        - staffId
        - reps
      properties:
        time:
          type: number
        reps:
          type: number
        staffId:
          type: number
    saveRawResultsRequest:
      type: object
      required:
        - data
      properties:
        data:
          type: string
    userInfoRequest:
      type: object
      required:
        - userTag
      properties:
        userTag:
          type: string
    staffInfoRequest:
      type: object
      required:
        - staffTag
      properties:
        staffTag:
          type: string
    machineActivateStep1Responce:
      type: object
      properties:
        data:
          type: object
          properties:
            machine:
              type: object
              properties:
                description:
                  type: string
                sku:
                  type: string
                type:
                  type: string
                serialNumber:
                  type: string
                imageUrl:
                  type: string
                rom:
                  type: integer
            gym:
              type: object
              properties:
                gymId:
                  type: string
                gymType:
                  type: string
                gymName:
                  type: string
    machineActivateStep2Responce:
      type: object
      properties:
        data:
          type: object
          properties:
            calibration:
              type: object
    getCalibrationDataResponse:
      type: object
      properties:
        data:
          type: object
    getTrainingResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            totalTime:
              type: number
            programName:
              type: string
            exercises:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  key:
                    type: string
                  type:
                    type: string
                  completed:
                    type: boolean
                  order:
                    type: number
                  params:
                    type: object
                    properties:
                      time:
                        type: number
                      cadence:
                        type: number
                      sensorMode:
                        type: string
                      minRange:
                        type: number
                      maxRange:
                        type: number
                      safeMaxRange:
                        type: number
                  machine:
                    type: object
                    properties:
                      type:
                        type: string
                      imageUrl:
                        type: string
                  instructions:
                    type: object
                    properties:
                      imageUrl:
                        type: string
                      description:
                        type: string
    saveCheckupResultsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              instructions:
                type: object
                properties:
                  imageUrl:
                    type: string
                  description:
                    type: string
              params:
                type: object
                properties:
                  time:
                    type: number
                  cadence:
                    type: number
                  sensorMode:
                    type: string
                  minRange:
                    type: number
                  maxRange:
                    type: number
                  safeMaxRange:
                    type: number
              id:
                type: number
              name:
                type: string
              key:
                type: string
              type:
                type: string
              completed:
                type: boolean
              order:
                type: number
              machine:
                type: object
                properties:
                  type:
                    type: string
                  imageUrl:
                    type: string
    userInfoResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
            imageUrl:
              type: string
            settings:
              type: object
              properties:
                language:
                  type: string
                unitOfMeasures:
                  type: string
    staffInfoResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: number
            firstName:
              type: string
            lastName:
              type: string
            imageUrl:
              type: string
            settings:
              type: object
              properties:
                language:
                  type: string
                unitOfMeasures:
                  type: string
    errorResponse:
      type: object
      required:
        - code
        - target
        - message
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              target:
                type: string
              message:
                type: string
              source:
                type: object
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
info:
  title: Mechano machine API
  description: This is API for mechano machine app
  version: 0.0.3
paths:
  /v1/machine/activate:
    post:
      operationId: machineActivateStep1V1
      summary: Machine activate
      description: The first step to activate the machine
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/machineActivateStep1Request'
        description: Hash and secure token
      parameters: []
      responses:
        '201':
          description: Machine Activator Info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/machineActivateStep1Responce'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
    put:
      operationId: machineActivateStep2V1
      summary: Machine activate
      description: The second step to activate the machine
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/machineActivateStep2Request'
        description: 'Hash, secure token and machine identifier'
      parameters: []
      responses:
        '200':
          description: Machine Calibration Data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/machineActivateStep2Responce'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/user/info:
    post:
      operationId: userInfoV1
      summary: User info
      description: Returns brief user information
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userInfoRequest'
        description: UserTag
      parameters:
        - name: Authorization
          in: header
          description: Machine
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Brief User Information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userInfoResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/staff/info:
    post:
      operationId: staffInfoV1
      summary: Staff info
      description: Returns brief staff information
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/staffInfoRequest'
        description: StaffTag
      parameters:
        - name: Authorization
          in: header
          description: Machine
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Brief Staff Information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/staffInfoResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/session/training:
    get:
      operationId: getTrainingV1
      summary: Get calibration data
      description: Returns a training program
      parameters:
        - name: Authorization
          in: header
          description: MachineStaffUser
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Training Program
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTrainingResponse'
        '403':
          description: Forbidden / Access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  '/v1/session/training/exercise/{id}/checkup':
    post:
      operationId: saveCheckupResultsV1
      summary: Save checkup results
      description: Saves exercise checkup results
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/saveCheckupResultsRequest'
        description: A checkup results object
      parameters:
        - name: id
          in: path
          description: The exercise id parameter
          required: true
          schema:
            type: number
        - name: Authorization
          in: header
          description: Machine
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Exercise data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/saveCheckupResultsResponse'
        '422':
          description: Unprocessable Entity / Invalid range
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  '/v1/session/training/exercise/{id}/workout':
    post:
      operationId: saveWorkoutResultsV1
      summary: Save workout results
      description: Saves exercise workout results
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/saveWorkoutResultsRequest'
        description: A workout results object
      parameters:
        - name: id
          in: path
          description: The exercise id parameter
          required: true
          schema:
            type: number
        - name: Authorization
          in: header
          description: Machine
          required: true
          schema:
            type: string
      responses:
        '208':
          description: Already Reported
          content: {}
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '422':
          description: Unprocessable Entity / Training is completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  '/v1/session/training/exercise/{id}/raw':
    post:
      operationId: saveRawResultsV1
      summary: Save raw results
      description: Saves exercise raw results
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/saveRawResultsRequest'
        description: Zip file in base64 encoding
      parameters:
        - name: id
          in: path
          description: The exercise id parameter
          required: true
          schema:
            type: number
        - name: Authorization
          in: header
          description: Machine
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
          content: {}
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '424':
          description: Failed Dependency / There are not results for the exercise
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/machine/calibration:
    get:
      operationId: getCalibrationDataV1
      summary: Get calibration data
      description: Returns calibration data of the desired machine
      parameters:
        - name: Authorization
          in: header
          description: Machine
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Machine Calibration Data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCalibrationDataResponse'
    post:
      operationId: uploadCalibrationDataV1
      summary: Upload calibration data
      description: Сreates or updates the calibration data of the desired machine
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/uploadCalibrationDataRequest'
        description: A calibration data object
      parameters:
        - name: Authorization
          in: header
          description: Machine
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
          content: {}
security:
  - Authorization: []
